export const TYPE = {
    SELECT: "SELECT",
    TEXT: "TEXT",
    EMAIL: "EMAIL",
    TEXTAREA: "TEXTAREA",
    PHONE: "PHONE",
    DATE: "DATE",
    IMAGE: "IMAGE",
    AUTO_COMPLETE_SELECT: "AUTO_COMPLETE_SELECT",
    NUMBER: "NUMBER",
    MULTI_SELECT: "MULTI_SELECT",
  };
  
  export const DEFAULT = {
    COUNTRY_CODE: "MA",
    CITY_NAME: "",
    POSTAL_CODE: "50000",
  };