export const PROFESSEUR = {
    MatriculePR: '',
    CINPR: '',
    CivilitePR: '',
    Phone1PR: '',
    Phone2PR: '',
    DateEmbauchePR: '',
    SalairePR: 0,
    NomBanquePR: '',
    RIBPR: '',
    MatriculeUT: '',
    // User fields (linked through MatriculeUT)
    UserNameUT: '',
    EmailUT: '',
    PhoneUT: '',
    RoleUT: '',
    StatutUT: '',
    NomPL: '',
    PrenomPL: '',
    GenrePL: '',
    AdressPL: '',
    VillePL: '',
    CodePostalPL: '',
    PaysPL: '',
    NationalitePL: '',
    LieuNaissancePL: '',
    DateNaissancePL: '',
    ObservationPL: '',
    ProfileFileNamePL: ''
};

